apiVersion: fastly.shopware.com/v1
kind: FastlySnippet
metadata:
  name: 10-pass
spec:
  content: |
    # --- START: SERVICE PINNING ---
    # https://developer.fastly.com/learning/concepts/shielding/#service-pinning
    call svc_pin_shield_fixup;
    # --- END: SERVICE PINNING ---

    # --- START: TRACEPARENT ---
    set bereq.http.traceparent = "00-" req.http.x-trace-id + "-" + req.http.x-trace-vcl-span-id "-01";

    # Avoid leaking internal headers to backends
    unset bereq.http.x-trace-id;
    unset bereq.http.x-trace-parent-span-id;
    unset bereq.http.x-trace-server-role;
    # --- END: TRACEPARENT ---
