{{- if not .Values.crds.installOnly }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: '{{ .Release.Name }}-fastly-operator'
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: manager
    app.kubernetes.io/created-by: fastly-operator
    app.kubernetes.io/instance: fastly-operator
    app.kubernetes.io/managed-by: fastly-operator
    app.kubernetes.io/name: deployment
    app.kubernetes.io/part-of: fastly-operator
    control-plane: fastly-operator
{{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
{{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: fastly-operator
  strategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: operator
        {{- with .Values.podAnnotations }}
            {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        control-plane: fastly-operator
    spec:
      {{- if hasKey .Values "affinity" }}
      affinity:
        {{- with .Values.affinity }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- else }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
                - arm64
              - key: kubernetes.io/os
                operator: In
                values:
                - linux
      {{- end }}
      tolerations:
        {{- with .Values.tolerations }}
          {{- toYaml . | nindent 10 }}
        {{- end }}
      containers:
      - args:
        command:
        - /manager
        env:
        - name: FASTLY_API_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Values.fastlyApiSecretRef.name }}
              key: {{ .Values.fastlyApiSecretRef.key }}
        - name: LEADER_ELECT
          value: "true"
        {{- if hasKey .Values "logLevel" }}
        - name: LOG_LEVEL
          value: "{{ .Values.logLevel }}"
        {{- end }}
        {{- if hasKey .Values "logFormat" }}
        - name: LOG_FORMAT
          value: "{{ .Values.logFormat }}"
        {{- end }}
        {{- if hasKey .Values "sources" }}
        - name: SOURCES
          value: "{{ .Values.sources | join "," }}"
        {{- end }}
        {{- if and (hasKey .Values "events") (hasKey .Values.events "nats") (.Values.events.nats.enable) }}
        - name: NATS_ADDRESS
          value: "{{ required "if nats is enabled set the address" .Values.events.nats.address }}"
        {{- if hasKey .Values.events.nats "topic" }}
        - name: NATS_TOPIC
          value: "{{ .Values.events.nats.topic | default "fastly-events" }}"
        {{- end }}
        {{- if hasKey .Values.events.nats "credentialsRef" }}
        - name: NATS_CREDENTIALS
          value: "/secrets/{{ .Values.events.nats.credentialsRef.key }}"
        {{- end }}
        {{- if hasKey .Values.events.nats "nkeyRef" }}
        - name: NATS_NKEY
          value: "/secrets/{{ .Values.events.nats.nkeyRef.key }}"
        {{- end }}
        {{- end }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: operator
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          {{- with .Values.resources }}
              {{- toYaml . | nindent 10 }}
          {{- end }}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        volumeMounts:
          {{- if and (hasKey .Values "events") (hasKey .Values.events "nats") (.Values.events.nats.enable) }}
          {{- if hasKey .Values.events.nats "nkeyRef" }}
          - mountPath: /secrets
            name: nkey
          {{- end }}
          {{- if hasKey .Values.events.nats "credentialsRef" }}
          - mountPath: /secrets
            name: credentials
          {{- end }}
          {{- end }}
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: '{{ .Release.Name }}-fastly-operator'
      terminationGracePeriodSeconds: 10
      volumes:
        {{- if and (hasKey .Values "events") (hasKey .Values.events "nats") (.Values.events.nats.enable) }}
        {{- if hasKey .Values.events.nats "nkeyRef" }}
        - name: nkey
          secret:
            secretName: {{ .Values.events.nats.nkeyRef.name }}
        {{- end }}
        {{- if hasKey .Values.events.nats "credentialsRef" }}
        - name: credentials
          secret:
            secretName: {{ .Values.events.nats.credentialsRef.name }}
        {{- end }}
        {{- end }}
{{- end }}
