apiVersion: v2
name: composable-frontends
description: A Helm chart for shopware/frontends
type: application
# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.2
# This value is equal to the used shopware frontends version.
appVersion: "1.16.0"
