{{- if and .Values.rbac.create (not .Values.crds.installOnly) -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "health-check-operator.fullname" . }}-manager-role
  labels:
    {{- include "health-check-operator.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - "*"
    resources:
      - "*"
    verbs:
      - get
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - create
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - list
  - apiGroups:
      - ""
    resources:
      - pods/log
      - secrets
    verbs:
      - get
  - apiGroups:
      - healthcheck.shopware.com
    resources:
      - customresourcechecks
      - httpchecks
      - natstriggers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - healthcheck.shopware.com
    resources:
      - customresourcechecks/finalizers
      - httpchecks/finalizers
      - natstriggers/finalizers
    verbs:
      - update
  - apiGroups:
      - healthcheck.shopware.com
    resources:
      - customresourcechecks/status
      - httpchecks/status
      - natstriggers/status
    verbs:
      - get
      - patch
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "health-check-operator.fullname" . }}-manager-rolebinding
  labels:
    {{- include "health-check-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "health-check-operator.fullname" . }}-manager-role
subjects:
  - kind: ServiceAccount
    name: {{ include "health-check-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "health-check-operator.fullname" . }}-leader-election-role
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "health-check-operator.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "health-check-operator.fullname" . }}-leader-election-rolebinding
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "health-check-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "health-check-operator.fullname" . }}-leader-election-role
subjects:
  - kind: ServiceAccount
    name: {{ include "health-check-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- if and .Values.metrics.enabled .Values.metrics.secure .Values.rbac.metricsAuth.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "health-check-operator.fullname" . }}-metrics-auth-role
  labels:
    {{- include "health-check-operator.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - authentication.k8s.io
    resources:
      - tokenreviews
    verbs:
      - create
  - apiGroups:
      - authorization.k8s.io
    resources:
      - subjectaccessreviews
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "health-check-operator.fullname" . }}-metrics-auth-rolebinding
  labels:
    {{- include "health-check-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "health-check-operator.fullname" . }}-metrics-auth-role
subjects:
  - kind: ServiceAccount
    name: {{ include "health-check-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "health-check-operator.fullname" . }}-metrics-reader
  labels:
    {{- include "health-check-operator.labels" . | nindent 4 }}
rules:
  - nonResourceURLs:
      - /metrics
    verbs:
      - get
{{- end }}
{{- end }}
