issuer: https://token.actions.githubusercontent.com
subject_pattern: repo:shopware\/shopware-operator:ref:refs\/tags\/.*

permissions:
  contents: write
  issues: write
  pull_requests: write
  members: read
