{{- if .Values.s3.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: aws-s3-credentials
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  AWS_ACCESS_KEY: {{ .Values.s3.accessKey | b64enc | quote }}
  AWS_SECRET_KEY: {{ .Values.s3.secretKey | b64enc | quote }}
{{- end }}
