{{- if and .Values.s3.enabled (not .Values.s3.useServiceAccount) }}
apiVersion: v1
kind: Secret
metadata:
  name: aws-s3-credentials
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  AWS_ACCESS_KEY: {{ .Values.s3.accessKeyID | b64enc | quote }}
  AWS_SECRET_KEY: {{ .Values.s3.secretAccessKey | b64enc | quote }}
{{- end }}
