{{ if hasKey .Values "blackfire" }}
{{ if hasKey .Values.blackfire "serverID" }}
{{ if hasKey .Values.blackfire "serverToken" }}
{{ if hasKey .Values.store "blackfire" }}
{{ if .Values.store.blackfire.enabled | default false }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopware-blackfire
  labels:
    app: blackfire
spec:
  replicas: 1
  selector:
      matchLabels:
        app: blackfire
  template:
      metadata:
        labels:
          app: blackfire
      spec:
        containers:
        - name: blackfire
          image: {{ .Values.blackfire.image | default "blackfire/blackfire:2" | quote }}
          env:
          - name: BLACKFIRE_SERVER_ID
            value: {{ .Values.blackfire.serverID }}
          - name: BLACKFIRE_SERVER_TOKEN
            value: {{ .Values.blackfire.serverToken }}
          ports:
          - containerPort: {{ .Values.blackfire.port | default 8307 }}
          resources:
            {{- with .Values.blackfire.resources }}
                {{- toYaml . | nindent 12 }}
            {{- end }}
---
# Service for blackfire
apiVersion: v1
kind: Service
metadata:
  name: {{ template "getBlackfireServiceName" . }}
  annotations:
    sidecar.istio.io/inject: "false"
spec:
  selector:
    app: blackfire
  ports:
    - protocol: TCP
      port: {{ .Values.blackfire.port | default 8307 }}
      targetPort: {{ .Values.blackfire.port | default 8307 }}
      appProtocol: tcp
{{ end }}
{{ end }}
{{ end }}
{{ end }}
{{ end }}
