{{ if .Values.useIstio | default false }}
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: "mts-policy"
spec:
  mtls:
    mode: STRICT
---
# https://github.com/kubernetes/ingress-nginx/issues/3171
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: minio
spec:
  hosts:
    - minio.{{ .Release.Namespace }}.svc.cluster.local
  http:
    - match:
        - port: 80
          headers:
            x-forwarded-host:
              exact: {{ template "generateS3URLApi" . }}
      route:
        - destination:
            host: minio.{{ .Release.Namespace }}.svc.cluster.local
            port:
              number: 80
          headers:
            request:
              set:
                Host:  {{ template "generateS3URLApi" . }}
    - match:
        - port: 80
      route:
        - destination:
            host: minio.{{ .Release.Namespace }}.svc.cluster.local
            port:
              number: 80
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: store-shopware
spec:
  hosts:
    - store-shopware.{{ .Release.Namespace }}.svc.cluster.local
  http:
    - match:
        - port: 8000
      route:
        - destination:
            host: store-shopware.{{ .Release.Namespace }}.svc.cluster.local
            port:
              number: 8000
          headers:
            request:
              set:
                Host: {{ .Values.applicationName}}.{{ .Values.projectName }}.{{ .Values.organizationName }}.{{ .Values.baseDomain }}
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: minio
spec:
  host: minio.{{ .Release.Namespace }}.svc.cluster.local
  trafficPolicy:
    outlierDetection:
      consecutive5xxErrors: 100
      interval: 1s
      baseEjectionTime: 1m
    loadBalancer:
      localityLbSetting:
        enabled: true
        distribute:
        - from: {{ .Values.region }}/{{ .Values.region }}a/*
          to:
            "{{ .Values.region }}/{{ .Values.region}}a/*": 80
            "{{ .Values.region }}/{{ .Values.region}}b/*": 10
            "{{ .Values.region }}/{{ .Values.region}}c/*": 10
        - from: {{ .Values.region }}/{{ .Values.region }}b/*
          to:
            "{{ .Values.region }}/{{ .Values.region}}a/*": 10
            "{{ .Values.region }}/{{ .Values.region}}b/*": 80
            "{{ .Values.region }}/{{ .Values.region}}c/*": 10
        - from: {{ .Values.region }}/{{ .Values.region }}c/*
          to:
            "{{ .Values.region }}/{{ .Values.region}}a/*": 10
            "{{ .Values.region }}/{{ .Values.region}}b/*": 10
            "{{ .Values.region }}/{{ .Values.region}}c/*": 80
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: store-shopware
spec:
  host: store-shopware.{{ .Release.Namespace }}.svc.cluster.local
  trafficPolicy:
    outlierDetection:
      consecutive5xxErrors: 100
      interval: 1s
      baseEjectionTime: 1m
    loadBalancer:
      localityLbSetting:
        enabled: true
        distribute:
          - from: {{ .Values.region }}/{{ .Values.region }}a/*
            to:
              "{{ .Values.region }}/{{ .Values.region}}a/*": 80
              "{{ .Values.region }}/{{ .Values.region}}b/*": 10
              "{{ .Values.region }}/{{ .Values.region}}c/*": 10
          - from: {{ .Values.region }}/{{ .Values.region }}b/*
            to:
              "{{ .Values.region }}/{{ .Values.region}}a/*": 10
              "{{ .Values.region }}/{{ .Values.region}}b/*": 80
              "{{ .Values.region }}/{{ .Values.region}}c/*": 10
          - from: {{ .Values.region }}/{{ .Values.region }}c/*
            to:
              "{{ .Values.region }}/{{ .Values.region}}a/*": 10
              "{{ .Values.region }}/{{ .Values.region}}b/*": 10
              "{{ .Values.region }}/{{ .Values.region}}c/*": 80
{{ end }}
