{{ if .Values.useIstio | default false }}
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: "mts-policy"
  namespace: '{{ .Release.Namespace }}'
spec:
  mtls:
    mode: STRICT
---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: disable-mtls-prometheus
  namespace: '{{ .Release.Namespace }}'
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus
  mtls:
    mode: DISABLE
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: store-shopware
  namespace: '{{ .Release.Namespace }}'
spec:
  hosts:
    - store-shopware.{{ .Release.Namespace }}.svc.cluster.local
  http:
    - match:
        - port: 8000
      route:
        - destination:
            host: store-shopware.{{ .Release.Namespace }}.svc.cluster.local
            port:
              number: 8000
          headers:
            request:
              set:
                Host: {{ .Values.applicationName}}.{{ .Values.projectName }}.{{ .Values.organizationName }}.{{ .Values.baseDomain }}
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: store-shopware
  namespace: '{{ .Release.Namespace }}'
spec:
  host: store-shopware.{{ .Release.Namespace }}.svc.cluster.local
  trafficPolicy:
    connectionPool:
      http:
        idleTimeout: 300s
      tcp:
        idleTimeout: 300s
        maxConnectionDuration: 70s
    outlierDetection:
      consecutive5xxErrors: 100
      interval: 1s
      baseEjectionTime: 1m
    loadBalancer:
      simple: LEAST_REQUEST
---
{{ end }}
