{{ if .Values.opensearch.enabled }}
apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name: {{ template "getOpenSearchClusterName" . }}
spec:
  general:
    httpPort: 9200
    serviceName: {{ template "getOpenSearchClusterName" . }}
    version: 2.8.0
  initHelper:
    resources:
       requests:
          memory: "1Gi"
          cpu: "500m"
       limits:
          memory: "1Gi"
          cpu: "500m"
  dashboards:
    enable: false
    version: 2.8.0
    replicas: 1
    resources:
      requests:
         memory: "512Mi"
         cpu: "200m"
      limits:
         memory: "512Mi"
         cpu: "200m"
  nodePools:
    - component: masters
      replicas: 3
      diskSize: "30Gi"
      nodeSelector:
      persistence:
        pvc:
          storageClass: gp3
          accessModes:
          - ReadWriteOnce
      resources:
         requests:
            memory: "4Gi"
            cpu: "1500m"
         limits:
            memory: "4Gi"
            cpu: "1500m"
      roles:
        - "master"
        - "data"
    - component: nodes
      replicas: 3
      diskSize: "30Gi"
      nodeSelector:
      persistence:
        pvc:
          storageClass: gp3
          accessModes:
          - ReadWriteOnce
      resources:
         requests:
            memory: "4Gi"
            cpu: "1500m"
         limits:
            memory: "4Gi"
            cpu: "1500m"
      roles:
        - "data"
    - component: coordinators
      replicas: 3
      diskSize: "30Gi"
      nodeSelector:
      persistence:
        pvc:
          storageClass: gp3
          accessModes:
          - ReadWriteOnce
      resources:
         requests:
            memory: "2Gi"
            cpu: "1500m"
         limits:
            memory: "2Gi"
            cpu: "1500m"
      roles:
        - "ingest"
    # - component: nodes
    #   topologySpreadConstraints:
    #     - maxSkew: 1
    #       topologyKey: topology.kubernetes.io/zone
    #       whenUnsatisfiable: DoNotSchedule
    #       labelSelector:
    #         matchLabels:
    #           app: shopware
    #       nodeAffinityPolicy: Honor
    #       nodeTaintsPolicy: Honor
    #   replicas: 3
    #   diskSize: "30Gi"
    #   nodeSelector:
    #   persistence:
    #     pvc:
    #       storageClass: gp3
    #       accessModes:
    #       - ReadWriteOnce
    #   resources:
    #      requests:
    #         memory: "2Gi"
    #         cpu: "500m"
    #      limits:
    #         memory: "2Gi"
    #         cpu: "500m"
    #   roles:
    #     - "cluster_manager"
    #     - "data"
{{ end }}
