{{- if .Values.store.serviceAccountName }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.store.serviceAccountName }}
  namespace: '{{ .Release.Namespace }}'
  {{- if .Values.serviceAccountAnnotations }}
  annotations:
    {{- toYaml .Values.serviceAccountAnnotations | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.store.automountServiceAccountToken | default false }}
{{- end }}
