apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: '{{ .Release.Name }}'
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "getStoreDeploymentName" . }}
  minReplicas: 1
  maxReplicas: 10
  behavior:
    scaleDown:
      policies:
        - type: Pods
          value: 1
          periodSeconds: 60
  metrics:
    - type: Pods
      pods:
        metric:
          name: phpfpm_process_utilization
        target:
          averageValue: "50"
          type: AverageValue
