apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "getMonologConfigName" . }}
  namespace: '{{ .Release.Namespace }}'
data:
  monolog.yaml: |
    monolog:
      {{- with .Values.store.monolog }}
        {{- toYaml . | nindent 6 }}
      {{- end }}
