{{ if hasKey .Values "minio" }}
{{ if hasKey .Values.minio "ingress" }}
{{ if .Values.minio.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: 'minio-s3-api'
  namespace: '{{ .Release.Namespace }}'
  annotations:
    {{- if .Values.minio.useTLS }}
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    {{- else }}
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    {{- end }}
    nginx.ingress.kubernetes.io/upstream-vhost: minio.{{ .Release.Namespace }}.svc.cluster.local
    {{- with .Values.minio.ingress.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.minio.ingress.className | quote }}
  rules:
    - host: {{ template "generateS3URLApi" . }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: minio
                port:
                  {{- if .Values.minio.useTLS }}
                  name: https-minio
                  {{- else }}
                  name: http-minio
                  {{- end }}
{{- if .Values.minio.ingress.tls }}
  tls:
  {{- .Values.minio.ingress.tls | toYaml | nindent 4 }}
{{- end }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: 'minio-console'
  namespace: '{{ .Release.Namespace }}'
  annotations:
    {{- if .Values.minio.useTLS }}
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    {{- else }}
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    {{- end }}
    nginx.ingress.kubernetes.io/upstream-vhost: shopware-minio-console.{{ .Release.Namespace }}.svc.cluster.local
    {{- with .Values.minio.ingress.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.minio.ingress.className | quote }}
  rules:
    - host: {{ template "generateS3URLConsole" .  }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: 'shopware-minio-console'
                port:
                  {{- if .Values.minio.useTLS }}
                  name: https-console
                  {{- else }}
                  name: http-console
                  {{- end }}
{{- if .Values.minio.ingress.tls }}
  tls:
  {{- .Values.minio.ingress.tls | toYaml | nindent 4 }}
{{- end }}
{{ end }}
{{ end }}
{{ end }}
