{{ if hasKey .Values "minio" }}
{{ if .Values.minio.enabled | default false }}
---
kind: Secret
apiVersion: v1
metadata:
  name: {{ template "getTenantUserSecretName" . }}
type: Opaque
stringData:
  CONSOLE_ACCESS_KEY: iVQFUj9Vy0EqP5pGSI
  CONSOLE_SECRET_KEY: rIfDdO920yef8Rawfh
{{ end }}
{{ end }}
